# Permalinks

# Setup
title: Rosetta open-source
description: Open-source projects by Rosetta
url: https://github.rosettatype.com
baseurl: ""

# About/contact
author:
  name: Rosetta
  url: https://rosettatype.com
  email: info@rosettatype.com

# Build settings
markdown: kramdown

# Articles showed on homepage
articles:
  - title: Eczar
    link: https://github.com/rosettatype/eczar
    description: Latin + Devanagari type family with 5 weights
  - title: Yrsa & Rasa
    link: https://github.rosettatype.com/yrsa-rasa
    description: Latin & Gujarati type families with 5 weights
  - title: repos
    link: https://github.com/rosettatype/repos
    description: Quick and dirty Python script to track multiple Git repositories and easily fetch updates
  - title: post-production scripts
    link: https://github.com/rosettatype/post-production-scripts
    description: Publicly available command-line tools used for post-production of Rosetta fonts
